name: mongo-action

on:
  push
  jobs:
  build-mongo:
    runs-on: ubuntu-latest
    container:
      image: mongo:latest
      options: --name mongo-container  

    steps:
    - name: Check MongoDB version
      run: mongod --version
